### ISSUE TITLE
Autocompletion is broken for web

### ISSUE THREAD

**Issue by felbinger** [pkgs-hub/vyatta-node_exporter#5]
vyos@vyos# set service monitoring node-exporter web 
  Invalid command: [Error:]

vbash: syntax error near unexpected token `in'

  Invalid command: [Error:]

vbash: syntax error near unexpected token `in'

Possible completions:
   web          node_exporter webserver configuration

**Comment by felbinger** [comment]
default value for txt element cant be int...
```yaml
# pkgs-hub/vyatta-node_exporter/deb/opt/vyatta/share/vyatta-cfg/templates/service/monitoring/node-exporter/web/max-requests/node.def
type: txt
help: Maximum number of parallel scrape requests. Use 0 to disable.
default: "40"  # <--- added quotes
```
